In [40]:
print('Inicio do EX. Dados de Imobiliarias')
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_excel('dataframe.xlsx', sheet_name='total por registro')
df.drop(0, inplace=True)
df.columns = df.iloc[0]
df.drop(1, inplace=True)
df.head()

Inicio do EX. Dados de Imobiliarias

1,MESORREGIÃO,NaN,Estado de São Paulo (TOTAL),Metropolitana de São Paulo (TOTAL),Região Metropolitana de São Paulo (RMSP),Município de São Paulo,Demais municípios da RMSP,Demais municípios da MSP,Ribeirão Preto,Campinas,...,Vale do Paraíba Paulista,Presidente Prudente,Macro Metropolitana Paulista,Piracicaba,Itapetininga,Assis,Araçatuba,Litoral Sul Paulista,Araraquara,Marília
2,ANO,MÊS,REGISTRO,REGISTRO,REGISTRO,REGISTRO,REGISTRO,REGISTRO,REGISTRO,REGISTRO,...,REGISTRO,REGISTRO,REGISTRO,REGISTRO,REGISTRO,REGISTRO,REGISTRO,REGISTRO,REGISTRO,REGISTRO
3,2012,2012-01-01 00:00:00,65055,23762,21751,14100,7651,2011,5285,8207,...,3335,1180,5517,2694,1478,1130,1510,1615,1450,773
4,2012,2012-02-01 00:00:00,70510,26162,24228,15767,8461,1934,6027,8034,...,3633,1274,6260,2900,1744,897,2086,1561,1942,912
5,2012,2012-03-01 00:00:00,83103,31204,29367,18900,10467,1837,7138,10023,...,4308,1458,7223,3475,1588,1162,1753,1722,2339,1215
6,2012,2012-04-01 00:00:00,76915,29354,26821,17503,9318,2533,5617,9007,...,4440,1287,6984,2674,1837,1038,1679,1595,2140,1113

IndexError: index 1 is out of bounds for axis 0 with size 0